# Generated by Django 2.2.10 on 2020-03-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-id',)},
        ),
    ]
